config/routes.rb
MedcostSaver::Application.routes.draw do
  devise_for :providers
  devise_for :admins
  get '/categories/new', controller: 'categories', action: 'new', as: 'new_category'
  post '/categories', controller: 'categories', action: 'create', as: 'categories'

  get '/categories', controller: 'categories', action: 'index'
  get '/categories/:id', controller: 'categories', action: 'show', as: 'category'

  get '/categories/:id/edit', controller: 'categories', action: 'edit', as: 'edit_category'
  patch '/categories/:id', controller: 'categories', action: 'update'

  delete '/categories/:id', controller: 'categories', action: 'destroy'

  root 'procedures#index'

  get '/procedures/search' => 'procedures#search'

  get '/locations/new', controller: 'locations', action: 'new', as: 'new_location'
  post '/locations', controller: 'locations', action: 'create', as: 'locations'

  get '/locations', controller: 'locations', action: 'index'
  get '/locations/:id', controller: 'locations', action: 'show', as: 'location'

  get '/locations/:id/edit', controller: 'locations', action: 'edit', as: 'edit_location'
  patch '/locations/:id', controller: 'locations', action: 'update'

  delete '/locations/:id', controller: 'locations', action: 'destroy'

  get '/companies/new', controller: 'companies', action: 'new', as: 'new_company'
  post '/companies', controller: 'companies', action: 'create', as: 'companies'

  get '/companies', controller: 'companies', action: 'index'
  get '/companies/:id', controller: 'companies', action: 'show', as: 'company'

  get '/companies/:id/edit', controller: 'companies', action: 'edit', as: 'edit_company'
  patch '/companies/:id', controller: 'companies', action: 'update'

  delete '/companies/:id', controller: 'companies', action: 'destroy'

  get '/offerings/new', controller: 'offerings', action: 'new', as: 'new_offering'
  post '/offerings', controller: 'offerings', action: 'create', as: 'offerings'

  get '/offerings', controller: 'offerings', action: 'index'
  get '/offerings/:id', controller: 'offerings', action: 'show', as: 'offering'

  get '/offerings/:id/edit', controller: 'offerings', action: 'edit', as: 'edit_offering'
  patch '/offerings/:id', controller: 'offerings', action: 'update'

  delete '/offerings/:id', controller: 'offerings', action: 'destroy'

  get '/procedures/new', controller: 'procedures', action: 'new', as: 'new_procedure'
  post '/procedures', controller: 'procedures', action: 'create', as: 'procedures'

  get '/procedures', controller: 'procedures', action: 'index'
  get '/procedures/:id', controller: 'procedures', action: 'show', as: 'procedure'

  get '/procedures/:id/edit', controller: 'procedures', action: 'edit', as: 'edit_procedure'
  patch '/procedures/:id', controller: 'procedures', action: 'update'

  delete '/procedures/:id', controller: 'procedures', action: 'destroy'

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :locations
  has_many :offerings
  has_many :procedures, :through => :offerings
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  def index
    @companies = Company.all
  end

  def show
    @company = Company.find_by(id: params[:id])
  end

  def new
  end

  def create
    @company = Company.new
    @company.name = params[:name]

    if @company.save
      redirect_to companies_url, notice: "Company created successfully."
    else
      render 'new'
    end
  end

  def edit
    @company = Company.find_by(id: params[:id])
  end

  def update
    @company = Company.find_by(id: params[:id])
    @company.name = params[:name]

    if @company.save
      redirect_to companies_url, notice: "Company updated successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @company = Company.find_by(id: params[:id])
    @company.destroy

    redirect_to companies_url, notice: "Company deleted."
  end
end

app/views/companies/edit.html.erb
<h1>Editing Company #<%= @company.id %></h1>

<%= form_tag(company_url(@company), method: 'patch') do %>
  <div>
    <%= label_tag :name %><br />
    <%= text_field_tag :name, @company.name %>
  </div>

  <div>
    <%= submit_tag "Update Company" %>
  </div>
<% end %>

app/views/companies/index.html.erb
<h1>Medical Service Providers</h1>

<% if admin_signed_in? %>

<p><%= link_to 'Add a New Company', new_company_url %></p>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @companies.each do |company| %>
    <tr>
      <td><%= company.name %></td>
      <td><%= link_to 'Show Procedures', company_url(company), class: 'btn btn-primary' %></td>
    <% if admin_signed_in? %>
      <td><%= link_to 'Edit', edit_company_url(company), class: 'btn btn-warning' %></td>
      <td><%= link_to 'Destroy', company_url(company), method: 'delete', data: { confirm: "Do you really want to delete this company?" }, class: 'btn btn-danger' %></td>
    <% else %>
      <td></td>
      <td></td>
    <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= form_tag(companies_url, method: 'post') do %>
  <div>
    <%= label_tag :name %><br />
    <%= text_field_tag :name %>
  </div>

  <div>
    <%= submit_tag "Create Company" %>
  </div>
<% end %>

app/views/companies/show.html.erb
<div>
<button type="button" class="btn btn-primary btn-block" disabled="disabled"><h3><%= @company.name %></h3></button>
</div>


<table class="table table-hover">
  <thead>
    <tr>
      <th>Procedure</th>
    </tr>
  </thead>


  <tbody>
    <% @company.procedures.order(:name).each do |procedure| %>
      <tr>
        <td><%= procedure.name %></td>
        <td><%= link_to '<i class="fa fa-search-plus"></i>'.html_safe, procedure_url(procedure), class: 'btn btn-primary' %></td>
        <% if admin_signed_in? %>
        <td><%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_procedure_url(procedure), class: 'btn btn-warning' %></td>
        <td><%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, procedure_url(procedure), method: 'delete', data: { confirm: "Do you really want to delete this procedure?" }, class: 'btn btn-danger' %></td>
         <% end %>
      </tr>
    <% end %>
  </tbody>
</table>