config/routes.rb
MedcostSaver::Application.routes.draw do
  devise_for :providers
  devise_for :admins
  get '/categories/new', controller: 'categories', action: 'new', as: 'new_category'
  post '/categories', controller: 'categories', action: 'create', as: 'categories'

  get '/categories', controller: 'categories', action: 'index'
  get '/categories/:id', controller: 'categories', action: 'show', as: 'category'

  get '/categories/:id/edit', controller: 'categories', action: 'edit', as: 'edit_category'
  patch '/categories/:id', controller: 'categories', action: 'update'

  delete '/categories/:id', controller: 'categories', action: 'destroy'

  root 'procedures#index'

  get '/procedures/search' => 'procedures#search'

  get '/locations/new', controller: 'locations', action: 'new', as: 'new_location'
  post '/locations', controller: 'locations', action: 'create', as: 'locations'

  get '/locations', controller: 'locations', action: 'index'
  get '/locations/:id', controller: 'locations', action: 'show', as: 'location'

  get '/locations/:id/edit', controller: 'locations', action: 'edit', as: 'edit_location'
  patch '/locations/:id', controller: 'locations', action: 'update'

  delete '/locations/:id', controller: 'locations', action: 'destroy'

  get '/companies/new', controller: 'companies', action: 'new', as: 'new_company'
  post '/companies', controller: 'companies', action: 'create', as: 'companies'

  get '/companies', controller: 'companies', action: 'index'
  get '/companies/:id', controller: 'companies', action: 'show', as: 'company'

  get '/companies/:id/edit', controller: 'companies', action: 'edit', as: 'edit_company'
  patch '/companies/:id', controller: 'companies', action: 'update'

  delete '/companies/:id', controller: 'companies', action: 'destroy'

  get '/offerings/new', controller: 'offerings', action: 'new', as: 'new_offering'
  post '/offerings', controller: 'offerings', action: 'create', as: 'offerings'

  get '/offerings', controller: 'offerings', action: 'index'
  get '/offerings/:id', controller: 'offerings', action: 'show', as: 'offering'

  get '/offerings/:id/edit', controller: 'offerings', action: 'edit', as: 'edit_offering'
  patch '/offerings/:id', controller: 'offerings', action: 'update'

  delete '/offerings/:id', controller: 'offerings', action: 'destroy'

  get '/procedures/new', controller: 'procedures', action: 'new', as: 'new_procedure'
  post '/procedures', controller: 'procedures', action: 'create', as: 'procedures'

  get '/procedures', controller: 'procedures', action: 'index'
  get '/procedures/:id', controller: 'procedures', action: 'show', as: 'procedure'

  get '/procedures/:id/edit', controller: 'procedures', action: 'edit', as: 'edit_procedure'
  patch '/procedures/:id', controller: 'procedures', action: 'update'

  delete '/procedures/:id', controller: 'procedures', action: 'destroy'

end

app/models/procedure.rb
class Procedure < ActiveRecord::Base
  has_many :offerings
  has_many :companies, :through => :offerings
  has_many :locations, :through => :companies
  belongs_to :category
end

app/models/procedure_type.rb
class ProcedureType < ActiveRecord::Base
end

app/controllers/procedures_controller.rb
class ProceduresController < ApplicationController

  def index
    @procedures = Procedure.all.order("name")
  end

  def search
    query = params[:procedure_name]
    p = Procedure.find_by(name: query)

    if p != nil
      # redirect_to "http://localhost:3000/procedures/#{p.id}"
      redirect_to procedure_url(p.id)
    else
      redirect_to procedures_url, notice: "Procedure not found."
    end

    # Find procedure using form data
    # If it exists, redirect to the show page
    # Else, redirect back to index with message

  end

  def show
    @procedure = Procedure.find_by(id: params[:id])

  end

  def new
  end

  def create
    @procedure = Procedure.new
    @procedure.name = params[:name]
    @procedure.category_id = params[:category_id]

    if @procedure.save
      redirect_to procedures_url, notice: "Procedure created successfully."
    else
      render 'new'
    end
  end

  def edit
    @procedure = Procedure.find_by(id: params[:id])
  end

  def update
    @procedure = Procedure.find_by(id: params[:id])
    @procedure.name = params[:name]
    @procedure.category_id = params[:category_id]

    if @procedure.save
      redirect_to procedures_url, notice: "Procedure updated successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @procedure = Procedure.find_by(id: params[:id])
    @procedure.destroy

    redirect_to procedures_url, notice: "Procedure deleted."
  end
end

app/views/procedures/edit.html.erb
<div class="page-header">
  <h1>Editing <%= @procedure.name %> Procedure</h1>
</div>

<%= form_tag(procedure_url(@procedure), method: 'patch', class: 'form-horizontal') do %>
  <div class="form-group">
    <%= label_tag :name, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :name, @procedure.name, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :category, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= select_tag :category_id, options_from_collection_for_select(Category.all, :id, :name, @procedure.category_id), class: 'form-control' %>
    </div>
  </div>


  <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
      <%= submit_tag "Update Procedure", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/procedures/index.html.erb
<div class="jumbotron">
  <h1>Sick Call</h1>
  <p>Discover and Compare Walk-in Clinic Prices. Save on Out-of-Pocket Expenses.</p>
</div>

<% if admin_signed_in? %>
<p><%= link_to 'Add a New Procedure', new_procedure_url, class: 'btn btn-primary' %></p>
<% end %>

<div>
<form action="/procedures/search">
  <label for="procedure_name">Search Procedures:</label>
  <input id="procedure_name" name="procedure_name" list="procedures" />
  <datalist id="procedures">
  <% @procedures.each do |procedure| %>
    <option value="<%= procedure.name %>">
  <% end %>
  </datalist>
  <input type="submit" value="Compare">
</form>
</div>

<div>
<h4>Not sure? Speak to a nurse at 1-800-SIC-CALL</h4>
</div>
<br>
<p></p>


  <%= link_to 'Browse by Category', categories_url, class: 'btn btn-primary' %>
  <%= link_to 'Browse by Medical Provider', companies_url, class: 'btn btn-primary' %>

<br>


<!--Create form with drop-down box displaying all categories.  When category is selected, display all procedures within that category

<br>
<#%= form_tag('/categories/', method: 'get', class: 'form-horizontal') do %>
  <div class="form-group">
    <#%= label_tag :category, nil, class: 'col-md-1 control-label' %>
    <div class="col-md-3">
      <#%= select_tag :category_id, options_from_collection_for_select(Category.all.order(:name), :id, :name), class: 'form-control'%>
<#% end %>

-->

<br>
<button type="button" class="btn btn-default btn-lg btn-block" disabled="disabled">Browse All Procedures</button>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th>Compare</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @procedures.each do |procedure| %>
      <tr>
        <td><%= procedure.name %></td>
        <td><%= procedure.category.name %> </td>
        <td><%= link_to '<i class="fa fa-search-plus"></i>'.html_safe, procedure_url(procedure), class: 'btn btn-primary' %></td>
        <% if admin_signed_in? %>
          <td><%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_procedure_url(procedure), class: 'btn btn-warning' %></td>
          <td><%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, procedure_url(procedure), method: 'delete', data: { confirm: "Do you really want to delete this procedure?" }, class: 'btn btn-danger' %></td>
        <% else %>
          <td></td>
          <td></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/procedures/new.html.erb
<div class="page-header">
  <h1>New Procedure</h1>
</div>

<%= form_tag(procedures_url, method: 'post', class: 'form-horizontal') do %>
  <div class="form-group">
    <%= label_tag :name, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :name, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :category, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= select_tag :category_id, options_from_collection_for_select(Category.all, :id, :name), class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
      <%= submit_tag "Create Procedure", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/procedures/show.html.erb
<div class="page-header">
  <h1><%= @procedure.name %></h1>
</div>

<div>
<h4>Find the best value</h4>
</div>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Price</th>
      <th>Note</th>
      <th>Company</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
    </tr>
  </thead>

<tbody>
    <% @procedure.offerings.order(:total_price).each do |offering| %>
      <% offering.locations.each do |location| %>
        <tr>
          <td><%= offering.total_price %></td>
          <td><%= offering.notes %></td>
          <td><%= offering.company.name %></td>
          <td><%= location.address1 %></td>
          <td><%= location.city %></td>
          <td><%= location.state %></td>
          <td><%= location.zip %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>