config/routes.rb
MedcostSaver::Application.routes.draw do
  devise_for :providers
  devise_for :admins
  get '/categories/new', controller: 'categories', action: 'new', as: 'new_category'
  post '/categories', controller: 'categories', action: 'create', as: 'categories'

  get '/categories', controller: 'categories', action: 'index'
  get '/categories/:id', controller: 'categories', action: 'show', as: 'category'

  get '/categories/:id/edit', controller: 'categories', action: 'edit', as: 'edit_category'
  patch '/categories/:id', controller: 'categories', action: 'update'

  delete '/categories/:id', controller: 'categories', action: 'destroy'

  root 'procedures#index'

  get '/procedures/search' => 'procedures#search'

  get '/locations/new', controller: 'locations', action: 'new', as: 'new_location'
  post '/locations', controller: 'locations', action: 'create', as: 'locations'

  get '/locations', controller: 'locations', action: 'index'
  get '/locations/:id', controller: 'locations', action: 'show', as: 'location'

  get '/locations/:id/edit', controller: 'locations', action: 'edit', as: 'edit_location'
  patch '/locations/:id', controller: 'locations', action: 'update'

  delete '/locations/:id', controller: 'locations', action: 'destroy'

  get '/companies/new', controller: 'companies', action: 'new', as: 'new_company'
  post '/companies', controller: 'companies', action: 'create', as: 'companies'

  get '/companies', controller: 'companies', action: 'index'
  get '/companies/:id', controller: 'companies', action: 'show', as: 'company'

  get '/companies/:id/edit', controller: 'companies', action: 'edit', as: 'edit_company'
  patch '/companies/:id', controller: 'companies', action: 'update'

  delete '/companies/:id', controller: 'companies', action: 'destroy'

  get '/offerings/new', controller: 'offerings', action: 'new', as: 'new_offering'
  post '/offerings', controller: 'offerings', action: 'create', as: 'offerings'

  get '/offerings', controller: 'offerings', action: 'index'
  get '/offerings/:id', controller: 'offerings', action: 'show', as: 'offering'

  get '/offerings/:id/edit', controller: 'offerings', action: 'edit', as: 'edit_offering'
  patch '/offerings/:id', controller: 'offerings', action: 'update'

  delete '/offerings/:id', controller: 'offerings', action: 'destroy'

  get '/procedures/new', controller: 'procedures', action: 'new', as: 'new_procedure'
  post '/procedures', controller: 'procedures', action: 'create', as: 'procedures'

  get '/procedures', controller: 'procedures', action: 'index'
  get '/procedures/:id', controller: 'procedures', action: 'show', as: 'procedure'

  get '/procedures/:id/edit', controller: 'procedures', action: 'edit', as: 'edit_procedure'
  patch '/procedures/:id', controller: 'procedures', action: 'update'

  delete '/procedures/:id', controller: 'procedures', action: 'destroy'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Sick Call</title>

  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootswatch/3.0.2/readable/bootstrap.min.css">
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.0.2/css/font-awesome.min.css">

<% if admin_signed_in? %>
  <style>
    /* Only necessary if you are using navbar-fixed-top */
    body {
      padding-top: 50px;
    }
  </style>
<% elsif provider_signed_in? %>
 <style>
    /* Only necessary if you are using navbar-fixed-top */
    body {
      padding-top: 50px;
    }
  </style>
<% else %>
<style>
    /* Only necessary if you are using navbar-fixed-top */
    body {
      padding-top: 10px;
    }
  </style>
<% end %>



  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>

<% if admin_signed_in? %>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to Rails.application.class.parent_name, root_url, :class => "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Categories", categories_url %></li>
        <li><%= link_to "Procedures", procedures_url %></li>
        <li><%= link_to "Offerings", offerings_url %></li>
        <li><%= link_to "Companies", companies_url %></li>
        <li><%= link_to "Locations", locations_url %></li>
        <li><%= link_to current_admin.email, edit_admin_registration_path%></li>
        <li><%= link_to "Logout", destroy_admin_session_path, :method => :delete %></li>
        <li><a href="#">About</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </nav>

  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to Rails.application.class.parent_name, root_url, :class => "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Categories", categories_url %></li>
        <li><%= link_to "Procedures", procedures_url %></li>
        <li><%= link_to "Offerings", offerings_url %></li>
        <li><%= link_to "Companies", companies_url %></li>
        <li><%= link_to "Locations", locations_url %></li>
        <li><%= link_to current_admin.email, edit_admin_registration_path%></li>
        <li><%= link_to "Logout", destroy_admin_session_path, :method => :delete %></li>
        <li><a href="#">About</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </nav>



<% elsif provider_signed_in? %>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to Rails.application.class.parent_name, root_url, :class => "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Categories", categories_url %></li>
        <li><%= link_to "Procedures", procedures_url %></li>
        <li><%= link_to "Offerings", offerings_url %></li>
        <li><%= link_to "Companies", companies_url %></li>
        <li><%= link_to "Locations", locations_url %></li>
        <li><%= link_to current_admin, edit_admin_registration_path%></li>
        <li><%= link_to "Logout", destroy_admin_session_path, :method => :delete %></li>
        <li><a href="#">About</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </nav>

  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to Rails.application.class.parent_name, root_url, :class => "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Categories", categories_url %></li>
        <li><%= link_to "Procedures", procedures_url %></li>
        <li><%= link_to "Offerings", offerings_url %></li>
        <li><%= link_to "Companies", companies_url %></li>
        <li><%= link_to "Locations", locations_url %></li>
        <li><%= link_to current_provider.email, edit_provider_registration_path%></li>
        <li><%= link_to "Logout", destroy_provider_session_path, :method => :delete %></li>
        <li><a href="#">About</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </nav>



<% else %>

<ul></ul>

<% end %>


  <div class="container">
    <% if notice.present? %>
      <div class="alert alert-dismissable alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= notice %>
      </div>
    <% end %>

<% if alert.present? %>
      <div class="alert alert-dismissable alert-warning">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= alert %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>